version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development

  code-runner:
    build:
      context: .
      dockerfile: Dockerfile.code-runner
    container_name: anrye-code-runner
    restart: unless-stopped
    # Keep container running
    command: tail -f /dev/null
