services:
  - type: web
    name: anrye-code-editor
    env: docker
    dockerfilePath: ./Dockerfile.cloudrun
    plan: free
    region: singapore
    branch: main
    env_vars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    scaling:
      minInstances: 1
      maxInstances: 1
