services:
  - type: web
    name: anrye-code-editor
    env: docker
    dockerfilePath: ./Dockerfile.cloudrun
    plan: free
    region: singapore
    branch: main
    scaling:
      minInstances: 1
      maxInstances: 1
